sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vedantdave77/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vedantdave77/react-test npm test

after_success:
  - docker build -t vedantdave77/docker-client ./client
  - docker build -t vedantdave77/docker-nginx ./nginx
  - docker build -t vedantdave77/docker-server ./server
  - docker build -t vedantdave77/docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vedantdave77/docker-client
  - docker push vedantdave77/docker-nginx
  - docker push vedantdave77/docker-server
  - docker push vedantdave77/docker-worker

  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-617431124156'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
    