sudo: required
services:
  - docker

before_install:
  - docker build -t vedantdave77/react-test -f ./client/Dockerfie.dev ./client

script:
  - docker run -e CI=true vedantdave77/react-test npm test

after_success:
  - docker build -t vedantdave77/docker-client ./client
  - docker build -t vedantdave77/docker-nginx ./nginx
  - docker build -t vedantdave77/docker-server ./server
  - docker build -t vedantdave77/docker-worker ./worker

 # Login to Docker CLI
 # Use username and password (with encrypted environment)
  # NOW, take each to docker hub for custom image repo.
